ARG OS_VER
FROM ubuntu:${OS_VER}
ARG USERINFO
RUN set -eux; \
    user=$(echo ${USERINFO}|cut -f1 -d:);\
    uid=$(echo ${USERINFO}|cut -f2 -d:);\
    group=$(echo ${USERINFO}|cut -f3 -d:);\
    group=$user;\
    gid=$(echo ${USERINFO}|cut -f4 -d:);\
    groupadd -g $gid $group;\
    useradd -m -u $uid -g $gid $user;\
    echo DONE
RUN set -eux;\
    apt-get update;\
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
 cloud-image-utils\
 curl\
 gpg\
 mkisofs\
 openssh-client\
 p7zip-full\
 whois\
    ; \
    apt-get clean; rm -rf /var/lib/apt/lists/*;\
    echo DONE
