ARG OS_VER
FROM debian:${OS_VER}
RUN set -eux;\
    apt-get update;\
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
 ca-certificates\
 debsums\
 dosfstools\
 fai-server\
 fai-setup-storage\
 make\
 python3-libcloud\
 python3-marshmallow\
 python3-pytest\
 python3-yaml\
 python3\
 qemu-utils\
 sudo\
 udev\
    ; \
    apt-get clean; rm -rf /var/lib/apt/lists/*;\
    echo DONE
ARG USERINFO
RUN set -eux; \
    user=$(echo ${USERINFO}|cut -f1 -d:);\
    uid=$(echo ${USERINFO}|cut -f2 -d:);\
    group=$(echo ${USERINFO}|cut -f3 -d:);\
    group=$user;\
    gid=$(echo ${USERINFO}|cut -f4 -d:);\
    groupadd -g $gid $group;\
    useradd -m -u $uid -g $gid $user;\
    usermod -aG sudo $user;\
    echo "$user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers;\
    echo DONE
