#!/bin/sh
set -eu
#set -x
this=$(dirname $0)
options=$this/data/var/ssh_options
while : ; do
    if [ -f $options ]; then
        exec cat $options
    fi
    if [ -f $options.done ]; then
        exit 1
    fi
    sleep 1
done
