#!/bin/sh
set -eu
#set -x
this=$(dirname $0)
cmd=$1
shift
data_dir=${DATA_DIR:-$this/data}
options=$data_dir/var/ssh_options
for n in $(seq 30); do
    if [ -f $options ]; then
        ssh_options="$(cat $options)"
        if [ -f $options.verified ]; then
            exec $cmd $ssh_options "$@"
        else
            if timeout 10s ssh $ssh_options true </dev/null; then
                touch $options.verified
                exec $cmd $ssh_options "$@"
            fi
        fi
    fi
    sleep 5
    if [ ! -f $options.started ]; then
        echo 'VM is not started' >&2
        exit 1
    fi
    if [ -f $options.done ]; then
        echo 'VM is exited' >&2
        exit 1
    fi
done
echo 'VM timeout' >&2
exit 1
